//%attributes = {"invisible":true}
var Button : Real
var Header1 : Real
var vRecNum : Text
var vShippingHT : Integer
var vShippingTTC : Integer
var vShippingVAT : Integer
var vTotal : Integer
var vTotalHT : Integer
var vTotalTTC : Integer
var vTotalVAT : Integer
var vVAT : Integer
var WParea : Object
var WPbuild : Object
var WPfragment : Object
var wp_MemoName : Text
var wp_Name : Text
var pictRange : Object
var vIcon : Picture
var vPict : Boolean
var wpTutorial : Object
var UpdateBookMark : Text
var Var1 : Text
var Var2 : Text
var vNumSec : Time
var WpAreaVisualizeDoc : Object
var vTher : Real
var vMessageGui : Text
var launchPreemptive : Time
var vMessageGuiCoop : Text
var vMessageGuiPreemp : Text
var vMessageGuiCompare : Text
var nbInvoicesCooperatif : Integer
var nbInvoicesPreemptif : Integer
